mode: parallel  #模式：balance（均衡模式）、parallel（平衡模式）
containers: #容器，可配置多个
  - address: http://192.168.31.233:5700 #青龙2.2、青龙2.8、v1v2v3v4v5访问地址
    username: admin #用户名
    password: admin #密码
    weigth: #权重 balance模式下权重越高分得的ck越多,默认1
    mode: parallel #单独对容器进行模式设置
    limit: 56 #限制容器ck数目
# - address: http://192.168.31.233:5700 #多容器自己配好，单容器就删掉下面3条
#   username: admin #用户名
#   password: admin #密码
# - path: /Users/cdle/Desktop/jd_study/jdc/config.sh #本地配置文件路径 v1v2v3v4v5和不知名容器的配置，青龙用户注释掉以下两行
# - path: /Users/cdle/Desktop/jd_study/jdc/list.sh
theme: https://ghproxy.com/https://raw.githubusercontent.com/cdle/jd_study/main/xdd/theme/noodin.html #自定义主题，支持本地、网络路径（我喜欢吃面）
static: ./static  #静态文件 便于自定义二维码页面时，引入css、js等文件（不用动）
master: #jd_xxxxx #管理员账户pin，有多个用'&'拼接
database: ql/db/.xdd.db  #数据库位置，默认./.jdc.db #（青龙填env.db文件路径，第一次部署就默认吧，改了麻烦）
qywx_key: #企业微信推送key（这个就是企业微信机器人的key）
daily_push: #定时任务（这个我暂时没有配置）
resident: #均衡模式下所有容器共同的账号pin，有多个用'&'拼接。不建议填写，后续实现指定账号助力功能。（这个我也没配置，多容器自己试试）
#数据库 支持sqlite3、mysql和postgres
#sqlite3: ql/.xdd #填路径，默认 ./.xdd
#mysql: user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
#postgres: host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai


#自定义ua
user_agent:
telegram_bot_token: #bot token（这个应该不用再说了吧）
telegram_user_id: #id（这个应该不用再说了吧）
qquid:  #接收通知的qq号（这个填你的群主qq号码，和扫码配置的qq机器人分开，需要2个qq号）
qqgid:  #监听的群（把你的羊毛群号填上去）
qbot_public_mode: true  #qq机器人群聊模式，默认私聊模式（我用了群测试，所以改了true，默认false）
default_priority: #新用户默认优先级（默认就行，默认是1）
no_ghproxy: true  #更新资源是否不使用代理 默认false（看你自己的运行环境填）
daily_asset_push_cron: 0 9 * * * #日常资产推送时间（这个应该也不用再说了吧）
tasks:
  - cron: 0 0 * * *
    path: https://raw.githubusercontent.com/cdle/xdd/main/scripts/jd_angryBean.js
    enable: true
    word: 抢京豆
    hack: true
    envs:
      - name: angryBeanPins
      - value: jd_xxxxx&jd_ooooo
  - path: https://raw.githubusercontent.com/shufflewzc/faker2/main/jd_all_bean_change.js
    word: 查询
